# Site settings
author: Dean Erickson
title: That's New to Me
header-img: img/home-bg.png
email: dmepilot@yahoo.com
copyright_name: Dean Erickson
description: > # this means to ignore newlines until "baseurl:"
  Finding Out What Else I Don't Know Yet...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dmepilot

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
